rtx.pathMaxBounces = 2
rtx.enableTransmissionApproximationInIndirectRays = True
rtx.postfx.vignetteRadius = 0.8
rtx.dlfg.enable = True
rtx.neuralRadianceCache.qualityPreset = 0
rtx.di.enableRayTracedBiasCorrection = False
rtx.graphicsPreset = 3
rtx.russianRouletteMaxContinueProbability = 0.7
rtx.neuralRadianceCache.smallestResolvableFeatureSizeMeters = 0.06
rtx.neuralRadianceCache.targetNumTrainingIterations = 2
rtx.enableUnorderedResolveInIndirectRays = False
rtx.russianRoulette1stBounceMinContinueProbability = 0.4
rtx.neuralRadianceCache.terminationHeuristicThreshold = 0.001
rtx.restirGI.biasCorrectionMode = 1
rtx.qualityDLSS = 4
rtx.enableUnorderedEmissiveParticlesInIndirectRays = False
rtx.postfx.chromaticCenterAttenuationAmount = 0.975
rtx.denoiseDirectAndIndirectLightingSeparately = False
rtx.volumetrics.froxelGridResolutionScale = 32
rtx.rayreconstruction.model = 0
rtx.postfx.vignetteSoftness = 0.1
rtx.restirGI.useReflectionReprojection = False
rtx.reflexMode = 1
rtx.postfx.enable = False
rtx.pathMinBounces = 0
rtx.enableStochasticAlphaBlend = False
rtx.resolutionScale = 0.66
